events {}

http {
  log_format json_combined escape=json
    '{
     "timestamp":"$time_iso8601",
     "ip":"$remote_addr",
     "method":"$request_method",
     "path":"$request_uri",
     "status":$status,
     "bytes_sent":$bytes_sent,
     "user_agent":"$http_user_agent",
     "referer":"$http_referer"
    }';

  access_log /var/log/nginx/access.log json_combined;
  error_log  /var/log/nginx/error.log;

  server {
    listen 80;

    # ── Frontend (React Vite) ─────────────────
    location / {
      proxy_pass http://frontend:5173;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # ── Log server (Node) ─────────────────────
    location /api/ {
      proxy_pass http://backend:3001/;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}